### ISSUE TITLE
Crash on server log-in

### ISSUE THREAD

**Issue by carstorm** [MinecraftModDevelopment/Project-Ultimate#1]
When I log into the server, I immediately crash. No crash log is created but here is two separate client.log files:

[Copied from discord server chat]
I was wondering why it's mid day and the server is empty. It's probaly due to crashing on server login, thogh no crash report is made, here is the client.log

https://justpaste.it/zawu
Here is anotehr client.log file that looked like it contained more useful info (IMO)
https://justpaste.it/zawy

**Comment by knoxhack** [comment]
try joining now

**Comment by carstorm** [comment]
[fml-client-latest.txt](https://github.com/MinecraftModDevelopment/Project-Ultimate/files/528531/fml-client-latest.txt)
Now java itself is crashing everytime I join the server, attached is the client.log file (renamed .txt so i can upload it)

**Comment by knoxhack** [comment]
no crash report?

**Comment by carstorm** [comment]
for this one no, it's java itself that is crashing when I join the server, happened 3 times so I know its not as one-off.

**Comment by knoxhack** [comment]
Try joining again
