### ISSUE TITLE
Server crash on login.

### ISSUE THREAD

**Issue by levaritie** [MinecraftModDevelopment/Project-Ultimate#10]
Hi Ruchia and me crash the server on log in.
we both have about the same equipment so I think its related to a item we have in our inventory.
I am very far away from the base atm while ruchia is in our base there for I drew this conclusion.
upon the update of the server I noticed a few thins, 1 the passwords things diamond infused armour changed to normal carbon armour. 2 we instantly crash the server so gathering data is not easy.
the only item I can think of that crashes the server is the calculator mod nutrition module. its a item that keeps your health and food full that way you dont need to eat, its convinient but it constanly keeps your food full so my thoery is that after the update for some reason it crashes the server, now I cant test this since logging in means I instantly crash even when I try to drop the item. 

other items in our inventory are a tartagic gem from blood magic, wich is like a battery for magic.
I have something that makes me constantly invisible sort of, but only I possese this item so since ruchia doest have it I can conclude it is not related. we both have a atomic disasembler from mekanism.
we both have the changed carbon armour. and a few other bits and bobs, wich I believe to be harmless.

there is something I would like to test though. if I am correct there is a admin command wich allows the admin to open op inventories like a chest from players, could our nutrition module be deleted from our inventory, the reason being not for a simple full whipe is ruchia has a draconic teleporter thingie with alot of locations stored, I dont know the details but she would like to keep those. if this is how ever not possible then a full wipe might be needed or maybe some of you have another idea that might solve this.

but if items could be deleted one by one then please allow one of use to try track down what causes it.

this is all I can think of what causes it because its hard to obtain data related to the crash.

Edit, Do keep in mind if the one by one items can be moved or deleted dont put them in your own inventory because if it is related to server crashes the curse will just transfer to you

Edit 2, its being worked on.

**Comment by Morpheus1101** [comment]
Providing a Crash log or fml-client-latest.log may prove to speed Knox or any of the other Public-Server admins in fixing this issue quickly for you both :)
