### ISSUE TITLE
Stuck after sleeping

### ISSUE THREAD

**Issue by Kename** [MinecraftModDevelopment/Project-Ultimate#2]
When using a bed to sleep, the screen gets stuck on the sleeping screen on waking. You can still interact with the chat, but not leave the bed. No recourse other than quiting out.

**Comment by Morpheus1101** [comment]
Sadly this bug has been an issue for a while and known, however the cause of this as far as im aware is unknown.

**Comment by knoxhack** [comment]
Vanilla Bug
