### ISSUE TITLE
Woot

### ISSUE THREAD

**Issue by DoctorFTB** [MinecraftModDevelopment/Project-Ultimate#3]
After put Mob Prism from Woot in Mob Controller - crash server and recoil.

**Comment by knoxhack** [comment]
No client crash?

**Comment by DoctorFTB** [comment]
No.

**Comment by Ipsis** [comment]
Since I'm the poor fool that wrote Woot -

Can you tell me what mob you had captured and the version of Woot that you were running and I'll try and replicate/fix the issue.

**Comment by knoxhack** [comment]
Oh I think it was a villager

**Comment by Ipsis** [comment]
I've downloaded the most recent Project-Ultimate  [1.0.9] and captured villagers and the non-vanilla mobs that are present. I can successfully program the controller and get a formed factory for each of these without crashing.

Granted I'm only running a single player instance, not a server.

I've also checked with a local server (not running Project-Ultimate) and can capture/program villagers with no issues.

So I'm a bit stuck as to what happened.
If you do have the problem again, if you can point me at the server crash output and I'll try and identify the issue from there.

**Comment by carstorm** [comment]
I'm guessing this is why the woot mod was removed from the server :(
