### ISSUE TITLE
Vienminer mod rejection

### ISSUE THREAD

**Issue by carstorm** [MinecraftModDevelopment/Project-Ultimate#6]
Having this issue again. Happened just after a server restart. If cause is unknown, maybe mod can be temporarily removed? 

![image](https://cloud.githubusercontent.com/assets/7497589/19557965/816137e8-968d-11e6-8c61-6d1ba4a7411d.png)

Adding issue here to have it remain on the radar till fixed.

**Comment by knoxhack** [comment]
A Server restart will fix it, Restarting
